### PR TITLE
fix(uncontrollable):  Migrate unsafe lifecycle

### PR DESCRIPTION
**Pull request by nortonwong**
Fixes https://github.com/jquense/uncontrollable/issues/32.

### CODE REVIEW

**Comment by slavagoreev** [comment]
Please, merge this PS asap. It is completely annoying to see those warnings!

**Comment by MatthewHerbst** [comment]
I believe this requires bumping the React minimum version to `^16.3.0`

**Comment by MatthewHerbst** [comment]
@jquense any chance we could fast-track merging this? Would help everyone who uses `react-boostrap`. This will be a breaking change to this library due to the peer dependency bump

**Comment by jquense** [comment]
Given that fixing properly is a breaking change using https://github.com/reactjs/react-lifecycles-compat is probably a better first step as it doesn't require a major bump and any downstream consumers would automatically get the update. 

I would suggest we do that first, release, and then remove bump the peer dep and cut a new major

**Comment by nortonwong** [comment]
@jquense Looking at React's changelog, Hooks were introduced in [16.8.0](https://github.com/facebook/react/blob/master/CHANGELOG.md#1680-february-6-2019). Since `useUncontrolled.js` imports Hooks, it seems like a new minimum `16.8.0` is needed anyway.

**Comment by jquense** [comment]
The minimum to use the hook is `16.8` yes, but not the HOC which is what is being updated here.

**Comment by nortonwong** [comment]
Ah, so that can be left as a run-time error. Okay.

**Comment by jquense** [comment]
awesome thanks!

**Pull request merged**
