### PR TITLE
Add Support React v16

### PR DESCRIPTION
**Pull request by vadimka123**

### CODE REVIEW

**Comment by jquense** [comment]
Hey there, thanks for the PR.  It sure I understand the change tho, string refs are still supported in v16

**Comment by vadimka123** [comment]
Hey, Jason
Yes, supported, but not in production build  (https://reactjs.org/docs/error-decoder.html?invariant=149&args[]=inner)

**Comment by jquense** [comment]
That's not quite what the error is saying. IN your producton build you have multiple instances of react, so switching the refs this way (which is a good change!) is actually hiding your underlying problem

**Comment by vadimka123** [comment]
Maybe you are right
A good change, so let's update

**Pull request closed without merging**
