### PR TITLE
Ensure compatibility with React >= 15

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jquense** [comment]
thanks!

**Comment by enten** [comment]
When do you will publish a 3.2.x version with this fix?

**Comment by cchamberlain** [comment]
When are you going to publish this? This is breaking react15 and react-bootstrap. Even publishing a beta tag would allow us to override the version react-bootstrap is using.  Short of that I'm going to have to fork this and react-bootstrap and publish separate packages.

**Comment by cchamberlain** [comment]
Published and working for me at https://www.npmjs.com/package/uncontrollable-react15 until the main repo gets bumped.

**Pull request merged**
